language: c
os: linux
dist: xenial
sudo: required

compiler:
  - m68k-atari-mint-gcc

before_install:
  - export USER=$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 1)
  - export BASE_RAW_URL="https://raw.githubusercontent.com/${USER}"

  - wget -O .travis/download_prerequisities.sh "${BASE_RAW_URL}/travis-scripts/master/download_prerequisities.sh"
  - sh ./.travis/download_prerequisities.sh
  - sh ./.travis/install-cross-mint.sh cross-mint-essential cflib-m68k-atari-mint > /dev/null
  - . ./.travis/install-udo.sh
  
before_script:
  - . ./.travis/setup_env.sh
  - export SHORT_ID=$(git log -n1 --format="%H" | cut -c 1-3)

script:
  - sh ./.travis/build.sh "${PWD}/.travis/tmp" "${PWD}/.travis/out"

deploy:
  provider: script
  skip_cleanup: true
  script: sh ./.travis/deploy.sh "${PWD}/.travis/out" $encrypted_a8c32f314d99_key $encrypted_a8c32f314d99_iv
  on:
    repo: freemint/qed
