void hl_init( void );
void hl_exit( void );
void hl_insert( RINGP rp, LINEP zp );
void hl_insert_block( RINGP rp, LINEP first, LINEP last );
void hl_remove( RINGP rp, LINEP zp );
void hl_remove_block( RINGP rp, LINEP first, LINEP last );
void hl_update( TEXTP t_ptr );
void hl_update_block( RINGP rp, LINEP first, LINEP last );
void hl_update_text( TEXTP t_ptr );
void hl_update_zeile( RINGP rp, LINEP z_ptr );
void hl_update_all( void );
void hl_init_text( TEXTP t_ptr );
void hl_free( TEXTP tp );
HL_LINE hl_get_zeile( LINEP z );
bool hl_read_syn(void);
bool hl_write_syn(void);
void hl_change_text_type( TEXTP t_ptr, char *extension );
void hl_disable(void);
void hl_enable(void);
